apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmna-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: numenera-api
  template:
    metadata:
      labels:
        app: numenera-api
    spec:
      containers:
        - name: api
          image: rdoneux/numenera:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "nmna-mysql"
            - name: APP_ENV
              value: "production"
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: "MYSQL_PORT"
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: "MYSQL_ROOT_PASSWORD"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: "MYSQL_DATABASE"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: "MYSQL_USER"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "mysql"
                  key: "MYSQL_ROOT_PASSWORD"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: "mysql"
                  key: "MYSQL_DATABASE"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "jwt"
                  key: "JWT_SECRET"
            - name: REFRESH_TOKEN_EXP_HOURS
              valueFrom:
                secretKeyRef:
                  name: "jwt"
                  key: "REFRESH_TOKEN_EXP_HOURS"
            - name: ACCESS_TOKEN_EXP_MINUTES
              valueFrom:  
                secretKeyRef:
                  name: "jwt"
                  key: "ACCESS_TOKEN_EXP_MINUTES"
---
apiVersion: v1
kind: Service
metadata:
  name: nmna-api
spec:
  selector:
    app: numenera-api
  type: NodePort
  ports:
    - port: 3000                 # internal service port
      targetPort: 3000           # container port
      nodePort: 30080            # port you hit externally
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nmna-api-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: nmna.dev   # replace with your domain or use your node IP for testing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nmna-api
                port:
                  number: 80