apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: rdoneux/migrate
          command: [
            "migrate",
            "-path", "/migrations",
            "-database", "mysql://${DB_USER}:${DB_PASSWORD}@tcp(db:${DB_PORT})/${DB_NAME}",
            "up"
          ]
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          hostPath:
            path: /path/to/your/migrations
      restartPolicy: Never