apiVersion: v1
kind: Service
metadata:
  name: nmna-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32306  # or let Kubernetes assign one
  selector:
    app: nmna-mysql