apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmna-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmna-mysql
  template:
    metadata:
      labels:
        app: nmna-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: "MYSQL_PORT"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: "MYSQL_ROOT_PASSWORD"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: "MYSQL_DATABASE"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: "MYSQL_USER"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "mysql"
                  key: "MYSQL_ROOT_PASSWORD"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
